services:
  fairseq:
    build: .
    volumes:
      - type: bind
        source: "/work00"
        target: "/work00"
      - type: bind
        source: "./fairseq"
        target: "/code/fairseq"
      - type: bind
        source: "./shell"
        target: "/code/shell"
    tty: true
    shm_size: '2gb'
    environment:
      HOST_USERNAME: ${HOST_USERNAME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # You must change these IDs depending on the server
              # e.g., if you use DGX series: `0, 1, 2, 4` to avoid using crappy GPU
              # e.g., otherwise: 0, 1, 2, 3
              device_ids: ['0', '1', '2', '3']
              capabilities: [gpu]
