version: "2.5"
services:
  bert:
    ports:
      - "8800:81"
    build: .
    volumes:
      - type: bind
        source: "/work00"
        target: "/work00" 
      - type: bind
        source: "/work00/$HOST_USERNAME/model/"
        target: "/model"
      - type: bind
        source: "/work00/$HOST_USERNAME/data/"
        target: "/data"
      - type: bind
        source: "/home/$HOST_USERNAME/Geo-Ent-in-LMs"
        target: "/code/Geo-Ent-in-LMs"
    tty: true
    shm_size: '2gb'
    environment:
      HOST_USERNAME: ${HOST_USERNAME}
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
      runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # You must change these IDs depending on the server
              # e.g., if you use DGX series: `0, 1, 2, 4` to avoid using crappy GPU
              # e.g., otherwise: 0, 1, 2, 3
              device_ids: ['0', '1', '2', '3']
              capabilities: [gpu]
